export const GET_POWERBANKS = 'BLOCK/GET_POWERBANKS';
export const REQUEST_POWERBANKS = 'BLOCK/REQUEST_POWERBANKS';
export const SAVE_TO_MY_POWERBANK = 'BLOCK/SAVE_TO_MY_POWERBANK';
export const CHANGE_POWERBANK_IN_STOCK = 'BLOCK/CHANGE_POWERBANK_IN_STOCK';